##
## AppVeyor
## https://www.appveyor.com/
##
## ReDefine
## https://github.com/rotators/ReDefine/
##
## Nigtly builds
## Linux, 32bit   https://ci.appveyor.com/api/projects/rotators/ReDefine/artifacts/ReDefine.zip?job=Image:%20Ubuntu;%20Platform:%20x32&branch=master&pr=false
## Linux, 64bit   https://ci.appveyor.com/api/projects/rotators/ReDefine/artifacts/ReDefine.zip?job=Image:%20Ubuntu;%20Platform:%20x64&branch=master&pr=false
## Windows, 32bit https://ci.appveyor.com/api/projects/rotators/ReDefine/artifacts/ReDefine.zip?job=Image:%20Visual%20Studio%202017;%20Platform:%20x32&branch=master&pr=false
## Windows, 64bit https://ci.appveyor.com/api/projects/rotators/ReDefine/artifacts/ReDefine.zip?job=Image:%20Visual%20Studio%202017;%20Platform:%20x64&branch=master&pr=false
##

version: "{build}"

image:
 - Ubuntu
 - Visual Studio 2017

platform:
 - x32
 - x64

#matrix:
# allow_failures:
#  - image: Ubuntu
#  - image: Visual Studio 2017

for:
 - matrix:
    only:
     - image: Ubuntu
     - image: Ubuntu1804
   clone_folder: /ReDefine
 - matrix:
    only:
     - image: Visual Studio 2017
   clone_folder: C:\ReDefine

#cache:
# - Cache -> CMakeLists.txt, Build.cmake

init:
 - sh: if [ "${PLATFORM}" == "x32" ]; then arch=i386; else arch=amd64; fi

install:
 - git submodule update --init --recursive
 - sh: sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sh: sudo apt-get update
 - sh: sudo apt-get install -y gcc-multilib g++-multilib
 - sh: hash -r

build_script:
 - cmake -P Build.cmake

after_build:
 - sh: file ${APPVEYOR_BUILD_FOLDER}/Build/ReDefine
 - sh:  7za a ReDefine.zip ${APPVEYOR_BUILD_FOLDER}/Build/ReDefine
 - cmd: 7z  a ReDefine.zip %APPVEYOR_BUILD_FOLDER%\Build\Release\ReDefine.exe

artifacts:
 - path: ReDefine.zip
